---
- name: Install monitoring packages
  zypper:
    name: "{{ uyuni_monitoring_packages }}"
  become: true
  when: uyuni_enable_monitoring

- name: Install monitoring Salt formulas
  become: true
  zypper:
    name: "{{ uyuni_monitoring_formulas_packages }}"
  when: uyuni_install_monitoring_formulas

- name: Enable monitoring
  command: mgr-monitoring-ctl enable
  args:
    creates:
  notify: Restart Uyuni

# TODO: enable monitoring in UI?
# POST rhn/manager/api/admin/config/monitoring
# {enable: true}
# Content-Type: application/json;charset=UTF-8
# DWRSESSIONID
# session
# pxt-session-cookie
