---
- name: Add GPG keys
  rpm_key:
    key: "{{ item }}"
  loop: "{{ uyuni_gpg }}"
  become: true

- name: Add Uyuni repositories
  zypper_repository:
    repo: "{{ item.url }}"
    name: "{{ item.name }}"
  loop: "{{ uyuni_repos }}"
  become: true
  when: uyuni_use_repo | bool
