---
# packages
uyuni_core_packages:
  - xfsprogs
  - lvm2
  - man
uyuni_repo: "https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/"
uyuni_packages:
  - patterns-uyuni_server
  - spacewalk-utils
  - spacecmd

# storage configuration
uyuni_use_lvm: false

# Uyuni configuration
uyuni_org_name: "Demo"
uyuni_org_login: "admin"
uyuni_org_password: "admin"

# firewall settings
uyuni_firewall_config: false
uyuni_firewall_default_zone: internal
uyuni_firewall_services:
  - suse-manager-server

# content settings
uyuni_cefs_setup: false
uyuni_cefs_setup_cronjob: false
uyuni_cefs_path: "/opt/errata-import"
uyuni_defs_setup: false
uyuni_defs_setup_cronjob: false
uyuni_cefs_packages:
  - perl
  - perl-Text-Unidecode
  - cron
uyuni_channels:
  - name: centos7
    arch: x86_64
  - name: centos7-updates
    arch: x86_64
